server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devopslearn
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # in dev, automatically update schema
    show-sql: true

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liGk7TJIp57N92Nu
            client-secret: 613ac8e99584aadbd7ec9cc9b13bf1db260bc62e
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
