server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devopslearn
    username: root
    password: yourpassword     # replace with your actual MySQL root password if different
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
